spring.application.name=demo
server.port=8080

# Tắt cache để sửa template không cần restart
spring.thymeleaf.cache=false

# ===== Cấu hình Bootstrap (TODO 3.5) =====
# true = offline (static/vendor), false = online (CDN)
app.bootstrap.offline=true

# ===== SQL Server (TODO 4.1) =====
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ThymeleafDemo;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=sa

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# String -> NVARCHAR để lưu tiếng Việt
spring.jpa.properties.hibernate.use_nationalized_character_data=true
spring.jpa.open-in-view=false
