spring.application.name=demo
server.port=8080

# Tắt cache để sửa template không cần restart
spring.thymeleaf.cache=false

# ===== Cấu hình Bootstrap (TODO 3.5) =====
# true = offline (static/vendor), false = online (CDN)
app.bootstrap.offline=true
