spring.application.name=chapter6

# C?u hình k?t n?i SQL Server

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=HSF302_CH6;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=sa
spring.datasource.driver-className=com.microsoft.sqlserver.jdbc.SQLServerDriver

# C?u hình Hibernate (T? ??ng t?o/c?p nh?t b?ng d?a trên Entity)
spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

